USE LABORATORIO;

CREATE TABLE MASCULINO
SELECT * FROM NACIMIENTOS WHERE SEXO = 'MASCULINO';
-- Corrección del nombre de la tabla
ALTER TABLE MASCULINO RENAME VARONES;

CREATE TABLE FEMENINO
SELECT * FROM NACIMIENTOS WHERE SEXO = 'FEMENINO';
-- Corrección del nombre de la tabla
ALTER TABLE FEMENINO RENAME MUJERES;

CREATE TABLE INDETERMINADOS
SELECT * FROM NACIMIENTOS WHERE SEXO = 'INDETERMINADO';

DROP TABLE NACIMIENTOS;