-- EJERCICIO 2
-- 2.1
USE LIBRERIA;
SET SQL_SAFE_UPDATES = 0;

UPDATE AUTORES
SET NOMBRE = 'Esteban'
WHERE APELLIDO = 'ECHEVERRÍA';
SELECT * FROM AUTORES;

-- 2.2
ALTER TABLE EMPLEADOS ADD PERMANENCIA INT;

UPDATE EMPLEADOS
SET PERMANENCIA = TIMESTAMPDIFF(YEAR, FECHA_INGRESO, CURDATE());
SELECT * FROM EMPLEADOS;

-- 2.3
ALTER TABLE LIBROS ADD PRECIO_PUBLICO FLOAT;

UPDATE LIBROS
SET PRECIO_PUBLICO = ROUND((PRECIO * 1.21), 2);
SELECT * FROM LIBROS;


-- EJERCICIO 3
-- 3.1
CREATE TABLE EMPLEADOS_ANTERIORES
SELECT * FROM EMPLEADOS
WHERE APELLIDO IN('THOMAS', 'PEREIRA', 'DEVO');
SELECT * FROM EMPLEADOS_ANTERIORES;

DELETE FROM EMPLEADOS
WHERE APELLIDO IN('THOMAS', 'PEREIRA', 'DEVO');
SELECT * FROM EMPLEADOS;

-- 3.2
INSERT INTO EMPLEADOS_ANTERIORES(EMPLEADO_ID, NOMBRE, APELLIDO, PUESTO_ID, EDITORIAL_ID, FECHA_INGRESO, PERMANENCIA)
SELECT EMPLEADO_ID, NOMBRE, APELLIDO, PUESTO_ID, EDITORIAL_ID, FECHA_INGRESO, PERMANENCIA
FROM EMPLEADOS
WHERE APELLIDO = 'CRUZ';

DELETE FROM EMPLEADOS
WHERE APELLIDO = 'CRUZ';
