USE LABORATORIO;

-- 1
SELECT IDCLIENTE, NOMBRECOMPANIA, CIUDAD, PAIS,
CASE
WHEN PAIS IN ('MEXICO', 'CANADA', 'USA') THEN 'AMERICA DEL NORTE'
WHEN PAIS IN ('ARGENTINA', 'BRASIL', 'VENEZUELA') THEN 'AMERICA DEL SUR'
ELSE 'EUROPA'
END AS 'CONTINENTE'
FROM CLIENTES_NEPTUNO
ORDER BY CONTINENTE, PAIS;

-- 2
SELECT IDPEDIDO, NOMBRECOMPANIA, FECHAPEDIDO, CARGO,
CASE
WHEN CARGO > 700 THEN 'EXCELENTE'
WHEN CARGO BETWEEN 500 AND 700 THEN 'MUY BUENO'
WHEN CARGO BETWEEN 250 AND 500 THEN 'BUENO'
WHEN CARGO BETWEEN 50 AND 250 THEN 'REGULAR'
ELSE 'MALO'
END AS 'EVALUACION'
FROM PEDIDOS_NEPTUNO
ORDER BY CARGO DESC;

-- 3
SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRECATEGORIA, PRECIOUNIDAD,
CASE
WHEN PRECIOUNIDAD > 100 THEN 'DELUXE'
WHEN PRECIOUNIDAD > 10 THEN 'REGULAR'
ELSE 'ECONOMICO'
END AS 'TIPO'
FROM PRODUCTOS_NEPTUNO
ORDER BY PRECIOUNIDAD DESC;
