USE LABORATORIO;

-- 1
CREATE TABLE EQUIPOS (EQUIPO VARCHAR (20) PRIMARY KEY);
SELECT * FROM EQUIPOS;

-- 2
INSERT INTO EQUIPOS
VALUES ('ARGENTINA'), ('BRASIL'), ('PARAGUAY'), ('CHILE'), ('URUGUAY'),
('COLOMBIA'), ('ECUADOR'), ('PERU'), ('BOLIVIA'), ('VENEZUELA');

-- 3
SELECT * FROM EQUIPOS AS L CROSS JOIN EQUIPOS AS V
WHERE L.EQUIPO <> V.EQUIPO
ORDER BY L.EQUIPO;

-- 4
SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRE_EMPLEADO FROM PRODUCTOS_NEPTUNO PN
CROSS JOIN EMPLEADOS E
WHERE PN.IDPRODUCTO = E.IDEMPLEADO;
