USE BONUS_TRACK;

SELECT CONCAT(ARTISTA, ' - ', TITULO) AS CANCION, GENERO FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT CONCAT_WS(' - ', ARTISTA, TITULO) AS CANCION, GENERO FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT CONCAT_WS(' - ', ARTISTA, TITULO) AS CANCION, UPPER(GENERO) AS GENERO FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT CONCAT_WS(' - ', ARTISTA, TITULO) AS CANCION, UPPER(GENERO), (YEAR(CURDATE()) - ANO) AS AÑOS FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT COUNT(*) CANCIONES FROM TOP_SPOTIFY;
SELECT ANO, COUNT(*) AS CANCIONES FROM TOP_SPOTIFY GROUP BY ANO; 
SELECT ANO, COUNT(*) AS CANCIONES FROM TOP_SPOTIFY GROUP BY ANO HAVING CANCIONES >= 50; 
