USE BONUS_TRACK;
-- Se importó la tabla TOP_SPOTIFY.

-- Ejercicio 1:
SELECT * FROM TOP_SPOTIFY;
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY;
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY GENERO;
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY GENERO, ARTISTA;

-- Ejercicio 2:
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO LIMIT 10;
SELECT ARTISTA, TITULO, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO LIMIT 5 OFFSET 10;
SELECT * FROM TOP_SPOTIFY WHERE ARTISTA = 'Madonna';
SELECT * FROM TOP_SPOTIFY WHERE GENERO = 'Pop' ORDER BY TITULO;
SELECT * FROM TOP_SPOTIFY WHERE GENERO = 'Pop' AND ANO = 2015 ORDER BY ARTISTA, TITULO;
SELECT * FROM TOP_SPOTIFY WHERE ANO < 2011 AND GENERO = 'Dance Pop' ORDER BY TITULO;

-- Ejercicio 3:
USE LIBRERIA;
SELECT * FROM AUTORES WHERE CIUDAD = 'Buenos Aires';
SELECT * FROM LIBROS WHERE PRECIO > 30 ORDER BY PRECIO DESC;
SELECT * FROM AUTORES WHERE PROVINCIA <> 'BA' ORDER BY PROVINCIA;
SELECT * FROM LIBROS WHERE CATEGORIA = 'Cuentos' AND PRECIO < 20 ORDER BY TITULO;
SELECT * FROM LIBROS WHERE CATEGORIA = 'Novelas' OR CATEGORIA = 'Ensayos' ORDER BY TITULO;
SELECT * FROM LIBROS WHERE PRECIO BETWEEN 20 AND 35 ORDER BY PRECIO;
SELECT * FROM AUTORES WHERE NOMBRE IN ('Jorge Luis', 'Victoria', 'Ernesto', 'Adolfo') ORDER BY NOMBRE;
SELECT * FROM LIBROS WHERE TITULO LIKE ('% mundo %') ORDER BY TITULO;
SELECT * FROM LIBROS WHERE TITULO LIKE ('% de %') ORDER BY TITULO;
SELECT * FROM LIBROS WHERE PRECIO IS NULL ORDER BY TITULO;