-- 1.1
USE BONUS_TRACK;
SET SQL_SAFE_UPDATES = 0;

UPDATE TOP_SPOTIFY
SET TITULO = UPPER(TITULO), ARTISTA = UPPER(ARTISTA);
SELECT * FROM TOP_SPOTIFY;

-- 1.2
ALTER TABLE TOP_SPOTIFY ADD PERMANENCIA INT;

UPDATE TOP_SPOTIFY
SET PERMANENCIA = YEAR(CURDATE()) - ANO;

-- 1.3
CREATE TABLE ULTIMOS_LANZAMIENTOS
SELECT * FROM TOP_SPOTIFY
WHERE PERMANENCIA <= 3;
SELECT * FROM ULTIMOS_LANZAMIENTOS;

DELETE FROM TOP_SPOTIFY
WHERE PERMANENCIA <=3;

-- 1.4
INSERT INTO TOP_SPOTIFY
VALUES (610, 'GOD CONTROL', 'MADONNA', 'POP', 2018, 3);

-- 1.5
INSERT INTO ULTIMOS_LANZAMIENTOS(ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA)
SELECT ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA
FROM TOP_SPOTIFY
WHERE PERMANENCIA <= 3;

DELETE FROM TOP_SPOTIFY
WHERE PERMANENCIA <= 3;
