USE LABORATORIO;

-- 1
SELECT PN.NOMBRECONTACTO, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNIDAD
FROM PROVEEDORES P JOIN PRODUCTOS_NEPTUNO PN
ON P.IDPROVEEDOR = PN.IDPROVEEDOR
ORDER BY PN.NOMBRECONTACTO, NOMBREPRODUCTO;

-- 2
SELECT PN.NOMBRECONTACTO, IDPRODUCTO, NOMBREPRODUCTO, PRECIOUNIDAD
FROM PROVEEDORES P, PRODUCTOS_NEPTUNO PN
WHERE P.IDPROVEEDOR = PN.IDPROVEEDOR
ORDER BY PN.NOMBRECONTACTO, NOMBREPRODUCTO;

-- 3
SELECT EMPRESA, NUMERO_PEDIDO, FECHA_PEDIDO, FORMA_PAGO
FROM CLIENTES C JOIN PEDIDOS P
ON C.COD_CLIENTE = P.CODIGO_CLIENTE
ORDER BY EMPRESA;

-- 4
SELECT EMPRESA, NUMERO_PEDIDO, FECHA_PEDIDO, FORMA_PAGO
FROM CLIENTES C LEFT JOIN PEDIDOS P
ON C.COD_CLIENTE = P.CODIGO_CLIENTE
WHERE P.NUMERO_PEDIDO IS NULL
ORDER BY EMPRESA;

-- 5
SELECT EMPRESA
FROM CLIENTES C LEFT JOIN PEDIDOS P
ON C.COD_CLIENTE = P.CODIGO_CLIENTE
WHERE P.NUMERO_PEDIDO IS NULL
ORDER BY EMPRESA;

-- 6
SELECT * FROM PROVEEDORES P LEFT JOIN PRODUCTOS_NEPTUNO PN
ON P.IDPROVEEDOR = PN.IDPROVEEDOR
WHERE PN.IDPRODUCTO IS NULL;

-- 7
SELECT * FROM PROVEEDORES P RIGHT JOIN PRODUCTOS_NEPTUNO PN
ON PN.IDPROVEEDOR = P.IDPROVEEDOR
WHERE P.IDPROVEEDOR IS NULL;
