USE LIBRERIA;

SELECT CONCAT(APELLIDO, ', ', NOMBRE) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;
SELECT CONCAT_WS(', ', APELLIDO, NOMBRE) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;
SELECT UPPER(CONCAT_WS(', ', APELLIDO, NOMBRE)) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;
SELECT UPPER(CONCAT(APELLIDO, ', ', LEFT(NOMBRE, 1), '.')) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;

SELECT CONCAT(APELLIDO, ', ', NOMBRE) AS EMPLEADO, YEAR(FECHA_INGRESO) AS 'AÑO DE INGRESO' FROM EMPLEADOS ORDER BY YEAR(FECHA_INGRESO) DESC;
SELECT CONCAT(APELLIDO, ', ', NOMBRE) AS EMPLEADO, YEAR(FECHA_INGRESO) AS 'AÑO DE INGRESO', TIMESTAMPDIFF(YEAR, FECHA_INGRESO, CURDATE()) AS ANTIGUEDAD FROM EMPLEADOS ORDER BY YEAR(FECHA_INGRESO) DESC;

SELECT MIN(PRECIO) AS 'MENOR PRECIO' FROM LIBROS;
SELECT MIN(PRECIO) AS 'MENOR PRECIO', MAX(PRECIO) AS 'MAYOR PRECIO' FROM LIBROS;
SELECT MIN(PRECIO) AS 'MENOR PRECIO', MAX(PRECIO) AS 'MAYOR PRECIO', ROUND(AVG(PRECIO), 2) AS 'PRECIO PROMEDIO' FROM LIBROS;
SELECT MIN(PRECIO) AS 'MENOR PRECIO', MAX(PRECIO) AS 'MAYOR PRECIO', ROUND(AVG(PRECIO), 2) AS 'PRECIO PROMEDIO', CATEGORIA FROM LIBROS GROUP BY CATEGORIA;
SELECT MIN(PRECIO) AS 'MENOR PRECIO', MAX(PRECIO) AS 'MAYOR PRECIO', ROUND(AVG(PRECIO), 2) AS 'PRECIO PROMEDIO', CATEGORIA FROM LIBROS GROUP BY CATEGORIA HAVING CATEGORIA <> 'SIN ASIGNAR';
